apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-belly
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-belly
            image: agriuseatstweets/belly:0.0.21
            resources:
              requests:
                cpu: "2"
                memory: "40Gi"
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/home/jupyter/work/keys/key.json"
              - name: BELLY_LOCATION
                value: "gs://spain-tweets/datalake"
              - name: BELLY_SIZE
                value: "360000"
              - name: PARTITION_SIZE
                value: "20000"
              - name: SPARK_DRIVER_MEMORY
                value: "40g"
              - name: BELLY_TOPIC
                value: "tweets"
              - name: KAFKA_BROKERS
                value: "kafka:9092"
              - name: KAFKA_CONSUMER_POLL_INTERVAL
                value: "1920000"
            volumeMounts:
              - name: keys
                mountPath: /home/jupyter/work/keys
                readOnly: true
          volumes:
            - name: keys
              secret:
                secretName: agrius-belly-keys
