apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-belly
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-belly
            image: agriuseatstweets/belly:0.0.1
            resources:
              requests:
                memory: "1024Mi"
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/home/jupyter/work/keys/key.json"
              - name: BELLY_LOCATION
                value: "gs://spain-tweets/datalake"
              - name: BELLY_SIZE
                value: "32000"
              - name: BELLY_TOPIC
                value: "tweets"
              - name: KAFKA_BROKERS
                value: "kafka:9092"
            volumeMounts:
              - name: keys
                mountPath: /home/jupyter/work/keys
                readOnly: true
          volumes:
            - name: keys
              secret:
                secretName: agrius-belly-keys
